name: Update Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required to push updates to gh-pages

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run stats script
        env:
          STEAM_ID: ${{ secrets.STEAM_ID }}
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          DISCORD_ID: ${{ secrets.DISCORD_ID }}
          DISCORD_BOT_KEY: ${{ secrets.DISCORD_BOT_KEY }}
          GIT_API_KEY: ${{ secrets.GIT_API_KEY }}
        run: |
          chmod +x setup-stats.sh
          ./setup-stats.sh

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy stats file to gh-pages
        run: |
          mv stats.json gh-pages/src/assets/stats.json
          cd gh-pages
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/assets/stats.json
          git commit -m "Update stats.json" || echo "No changes to commit"
          git push
